### ISSUE TITLE
Arbitrary `assert` statements in some models break reproducibility

### ISSUE THREAD

**Issue by neel04** [aks2203/deep-thinking#7]
https://github.com/aks2203/deep-thinking/blob/6b8aa99bfc3456541cc842d67f93a3fa41aa9055/deepthinking/models/feedforward_net_1d.py#L65

Hi, congrats on the NeurIPS pub! I was fiddling around with the codebase, but it appears that there is an assert which blocks running the model for test iterations greater than [`max_iters`](https://github.com/aks2203/deep-thinking/blob/6b8aa99bfc3456541cc842d67f93a3fa41aa9055/deepthinking/models/feedforward_net_1d.py#L52) so the model can't be run for more iterations it was trained for.

Additionally, its present only for the `feedforward_1D` or `2D` net - `DTNet` seems fine. Do you have any idea why this was there, because I assume it would prevent reproducibility for OOD generalization..

**Comment by aks2203** [comment]
Hi there! The feedforward models are defined with a fixed depth. This assert is appropriate as there is no way to add depth after training. The reason the forward method takes these args is so that the interface matches the recurrent models, but the assert statement makes sure that the indexing on line 73 works as intended.

Does that help clear things up?

**Comment by neel04** [comment]
It does. Thanks a lot!
